# Generated by Django 2.1.7 on 2019-08-27 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accredited_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('affiliated_body', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_esthablishment', models.DateField(blank=True, null=True)),
                ('website', models.URLField()),
                ('principal', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_person_number', models.CharField(max_length=13)),
                ('contact_person_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('lattitude', models.CharField(blank=True, max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.TextField()),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegesetup.Approval')),
                ('approved_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegesetup.Accredited_Body')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
