# Generated by Django 2.1.7 on 2019-08-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegesetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesetup',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basesetup',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collegesetup.Approval'),
        ),
        migrations.AlterField(
            model_name='basesetup',
            name='approved_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collegesetup.Accredited_Body'),
        ),
        migrations.AlterField(
            model_name='basesetup',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basesetup',
            name='contact_person_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='basesetup',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
