# Generated by Django 2.1.7 on 2019-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegesetup', '0002_auto_20190827_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
