# Generated by Django 2.1.7 on 2019-08-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegesetup', '0003_affiliatedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesetup',
            name='affiliated_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collegesetup.AffiliatedTo'),
        ),
    ]
