# Generated by Django 2.1.7 on 2019-08-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegesetup', '0004_auto_20190827_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesetup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
